### ISSUE TITLE
Workflow and Task with the same name does not work

### ISSUE THREAD

**Issue by pylebecq** [zenaton/zenaton-javascript#2]
When I define a workflow and a task having the same name, the execution crashes at some point. It seems like we're trying to run the task as if we are running a workflow so we don't provide the done() callback function to the task.

For example, I defined a Workflow named `HelloZenaton`:

```js
var { Workflow } = require("zenaton");

var Task = require("../Tasks/LaunchHelloZenaton");

module.exports = Workflow("HelloZenaton", function() {
  console.log('HelloZenaton workflow starts');
  new Task().execute();
  console.log('HelloZenaton workflow ends');
});
```

I define the task `LaunchHelloZenaton`, that will in turn execute a task having the same name as the workflow:

```js
var {Task} = require("zenaton");
var HelloZenaton = require("./HelloZenaton");

module.exports = Task("LaunchHelloZenaton", function(done) {
  console.log("LaunchHelloZenaton task starts");
  new HelloZenaton().execute();
  console.log("LaunchHelloZenaton task ends");
  done(null, "LaunchHelloZenaton");
});
```

And the last task definition, having the same name as the workflow:

```js
var {Task} = require("zenaton");

module.exports = Task("HelloZenaton", function(done) {
  console.log("HelloZenaton task starts");
  console.log("HelloZenaton task ends")
  done(null, "HelloZenaton");
});
```

Now if you try running this workflow, for example using the following code:

```js
require("./client");

var AsynchronousWorkflow = require("./Workflows/HelloZenaton");
new AsynchronousWorkflow().dispatch();
```

Then it crashes at some point. This is the content found in `zenaton.err` file:

```
/Users/pierre-yves/dev/core/worker/libraries/javascript/lib/Worker/v1/Worker.js:29
throw e;
^

TypeError: done is not a function
at /Users/pierre-yves/dev/examples-node/Tasks/HelloZenaton.js:6:3
at /Users/pierre-yves/dev/core/worker/libraries/javascript/lib/Worker/v1/Processor.js:45:28
at Array.forEach (<anonymous>)
at module.exports.processFromTask (/Users/pierre-yves/dev/core/worker/libraries/javascript/lib/Worker/v1/Processor.js:42:11)
at module.exports.process (/Users/pierre-yves/dev/core/worker/libraries/javascript/lib/Worker/v1/Processor.js:28:19)
at Engine.execute (/Users/pierre-yves/dev/examples-node/node_modules/zenaton/lib/v1/Engine/Engine.js:50:27)
at TaskClass.execute (/Users/pierre-yves/dev/examples-node/node_modules/zenaton/lib/v1/Tasks/AbstractTask.js:16:25)
at /Users/pierre-yves/dev/examples-node/Tasks/LaunchHelloZenaton.js:7:22
at Worker.process (/Users/pierre-yves/dev/core/worker/libraries/javascript/lib/Worker/v1/Worker.js:19:17)
at Slave.processJob (/Users/pierre-yves/dev/core/worker/libraries/javascript/lib/Loader/Slave.js:59:51)
```

**Comment by pylebecq** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [If user's define a task and a workflow to have the same name, there will be a problem in node.](https://trello.com/c/K9UJhpfr/499-if-users-define-a-task-and-a-workflow-to-have-the-same-name-there-will-be-a-problem-in-node)

**Comment by mKurrels** [comment]
@pylebecq  I think that as a fix you shouldn't be able to make a task that has the same name as a workflow. Because actually we have these flags "handle_only" and "handle_except" that take class definitions. And those class definitions are just a comma separated list of classes that don't specify if they are tasks or workflows. So you'll have a problem there as well. What do you think?

**Comment by pylebecq** [comment]
Yes, you're probably right. I guess that's a limitation we can enforce for now. If someday we can release it, then we will. In any case, it's still better than having a crash as it is now.

**Comment by geomagilles** [comment]
Closing this as outdated
