### ISSUE TITLE
No Init check library side: provided variable or connection

### ISSUE THREAD

**Issue by jalric** [zenaton/zenaton-javascript#21]
No errors are triggered when I init Zenaton client like this

`Zenaton.init(emptyVariable, null, '')`

Checks can be implemented code client side like in `zenaton/exemples-node` but is more the concern of the library. If I omit to implement checks and provide empty environment variables, no errors are displayed until I launch a workflow.

Improvement proposal: 
Some library like elasticsearch client provide method to check connection.
Can be useful when deploy in production.

```
var elasticsearch = require('elasticsearch');
var client = new elasticsearch.Client({
  host: 'localhost:9200',
  log: 'trace'
});

client.ping({
  requestTimeout: 30000,
}, function (error) {
  if (error) {
    console.error('elasticsearch cluster is down!');
  } else {
    console.log('All is well');
  }
});
```

**Comment by geomagilles** [comment]
I close this as this is not relevant anymore with v0.7
